services:
  businnescard1:
    image: businnescard1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8080:7000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "server.js"]
